### ISSUE TITLE
数据库呢？

### ISSUE THREAD

**Issue by wujianming** [felixzhu1989/Compass#1]
无法跑

**Comment by felixzhu1989** [comment]
我更新了SQLServerDB
1.在SQL数据库中打开CompassDB.sql文件，建立数据库
2.打开CompassDB_Table.sql添加表
3.打开CompassDB_Constraint.sql建立表间关系
4.CompassDB_Model.sql里边是我们公司的模型数据，
你也可以加，但是没法实际作图，因为SW模型文件再公司的电脑的PDM上，这个不能上传
https://www.bilibili.com/video/BV1ra4y1v7Mk
学习视频
https://www.bilibili.com/video/BV1LE411K7ro
